/*
 * Copyright 2025 The Kubernetes Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { makeCustomResourceClass } from '@kinvolk/headlamp-plugin/lib/Crd';

/** Package phases from status.phase (UDS operator, v1alpha1). */
export type PackagePhase =
  | 'Pending'
  | 'Ready'
  | 'Failed'
  | 'Retrying'
  | 'Removing'
  | 'RemovalFailed';

/** Colors accepted by Headlamp's StatusLabel component. */
export type StatusKind = 'success' | 'warning' | 'error' | '';

/** A Kubernetes-style status condition (status.conditions[]). */
export interface PackageCondition {
  type: string;
  status: 'True' | 'False' | 'Unknown';
  reason: string;
  message: string;
  lastTransitionTime: string;
  observedGeneration?: number;
}

/** An authservice-protected client (status.authserviceClients[]). */
export interface AuthserviceClient {
  clientId: string;
  selector?: Record<string, string>;
}

/** Observed state of a Package (status). All fields optional: the operator
 *  populates them over the reconcile lifecycle, and RBAC-limited reads may omit
 *  the whole object. */
export interface PackageStatus {
  phase?: PackagePhase;
  meshMode?: 'ambient' | 'sidecar';
  observedGeneration?: number;
  retryAttempt?: number;
  networkPolicyCount?: number;
  authorizationPolicyCount?: number;
  endpoints?: string[];
  monitors?: string[];
  probes?: string[];
  ssoClients?: string[];
  authserviceClients?: AuthserviceClient[];
  conditions?: PackageCondition[];
}

/** An exposed service on an Istio gateway (spec.network.expose[]). */
export interface ExposeEntry {
  host: string;
  service?: string;
  port?: number;
  targetPort?: number;
  gateway?: string;
  domain?: string;
  selector?: Record<string, string>;
  description?: string;
  /** @deprecated use selector */
  podLabels?: Record<string, string>;
  advancedHTTP?: Record<string, unknown>;
  match?: Array<Record<string, unknown>>;
}

/** Sources/targets generated by name rather than an explicit CIDR/selector. */
export type RemoteGenerated =
  | 'KubeAPI'
  | 'KubeNodes'
  | 'IntraNamespace'
  | 'CloudMetadata'
  | 'Anywhere';

/** A generated NetworkPolicy rule (spec.network.allow[]). */
export interface AllowRule {
  direction: 'Ingress' | 'Egress';
  description?: string;
  remoteGenerated?: RemoteGenerated;
  remoteNamespace?: string;
  remoteCidr?: string;
  remoteHost?: string;
  remoteProtocol?: 'TLS' | 'HTTP' | 'TCP' | 'UDP';
  remoteSelector?: Record<string, string>;
  remotePodLabels?: Record<string, string>;
  remoteServiceAccount?: string;
  port?: number;
  ports?: number[];
  selector?: Record<string, string>;
  podLabels?: Record<string, string>;
  labels?: Record<string, string>;
  serviceAccount?: string;
}

/** A Prometheus Pod/Service monitor (spec.monitor[]). */
export interface MonitorEntry {
  kind?: 'PodMonitor' | 'ServiceMonitor';
  portName: string;
  targetPort: number;
  selector: Record<string, string>;
  podSelector?: Record<string, string>;
  path?: string;
  description?: string;
  fallbackScrapeProtocol?: string;
  authorization?: {
    type?: string;
    credentials: { key: string; name?: string; optional?: boolean };
  };
}

/** A Keycloak protocol mapper on an SSO client (spec.sso[].protocolMappers[]). */
export interface ProtocolMapper {
  name: string;
  protocol: 'openid-connect' | 'saml';
  protocolMapper: string;
  config?: Record<string, string>;
  consentRequired?: boolean;
}

/** A Keycloak/SSO client configuration (spec.sso[]). */
export interface SsoClient {
  clientId: string;
  name: string;
  protocol?: 'openid-connect' | 'saml';
  clientAuthenticatorType?: 'client-secret' | 'client-jwt';
  description?: string;
  enabled?: boolean;
  publicClient?: boolean;
  standardFlowEnabled?: boolean;
  serviceAccountsEnabled?: boolean;
  alwaysDisplayInConsole?: boolean;
  redirectUris?: string[];
  webOrigins?: string[];
  rootUrl?: string;
  baseUrl?: string;
  adminUrl?: string;
  defaultClientScopes?: string[];
  groups?: { anyOf?: string[] };
  enableAuthserviceSelector?: Record<string, string>;
  attributes?: Record<string, string>;
  protocolMappers?: ProtocolMapper[];
  secret?: string;
  secretName?: string;
}

/** CA bundle configuration (spec.caBundle). */
export interface CaBundle {
  configMap?: {
    name?: string;
    key?: string;
    annotations?: Record<string, string>;
    labels?: Record<string, string>;
  };
}

/** Network configuration (spec.network). */
export interface PackageNetwork {
  expose?: ExposeEntry[];
  allow?: AllowRule[];
}

/** Desired state of a Package (spec). */
export interface PackageSpec {
  network?: PackageNetwork;
  sso?: SsoClient[];
  monitor?: MonitorEntry[];
  caBundle?: CaBundle;
}

/** Map a Package status.phase to a StatusLabel color. Pure; unknown -> ''. */
export function phaseToStatus(phase: string | undefined): StatusKind {
  switch (phase) {
    case 'Ready':
      return 'success';
    case 'Pending':
    case 'Retrying':
    case 'Removing':
      return 'warning';
    case 'Failed':
    case 'RemovalFailed':
      return 'error';
    default:
      return '';
  }
}

/**
 * The Package custom resource (packages.uds.dev/v1alpha1, namespaced).
 *
 * Imported from the top-level `/lib/Crd` re-export, NOT a deep submodule path
 * (the deep-import landmine).
 */
export const Package = makeCustomResourceClass({
  apiInfo: [{ group: 'uds.dev', version: 'v1alpha1' }],
  kind: 'Package',
  pluralName: 'packages',
  singularName: 'package',
  isNamespaced: true,
});

/** A Package KubeObject instance (as returned by useList()/useGet()). */
export type PackageObject = InstanceType<typeof Package>;

/**
 * Typed status accessor. The KubeObject `.status` getter is loosely typed
 * (KubeCRD), so read from `jsonData` and narrow to our schema. Returns
 * undefined when absent (fresh/RBAC-limited reads).
 */
export function packageStatus(pkg: PackageObject): PackageStatus | undefined {
  return pkg.jsonData?.status as PackageStatus | undefined;
}

/** Typed spec accessor. See packageStatus for the jsonData rationale. */
export function packageSpec(pkg: PackageObject): PackageSpec | undefined {
  return pkg.jsonData?.spec as PackageSpec | undefined;
}
